### PR TITLE
Support for flutter 1.22.0

### PR DESCRIPTION
**Pull request by krishnakumarcn**
Portal dependencies changed

### CODE REVIEW

**Comment by fayeed** [comment]
@krishnakumarcn Can you explain whats it the PR for, in brief Thanks!

**Comment by krishnakumarcn** [comment]
The previous version of flutter_mentions i.e., 1.0.1 is not working with flutter version 1.22.0.
I could see that the flutter_portal dependency in the version 1.0.1 is not updated to the latest portal version which is 0.3.0 which is updated specifically to support flutter 1.22.0.

So that's the only change.

**Comment by fayeed** [comment]
Yeah so can you create a new PR with that change alone that would be great.

**Comment by krishnakumarcn** [comment]
> The previous version of flutter_mentions i.e., 1.0.1 is not working with flutter version 1.22.0.
> I could see that the flutter_portal dependency in the version 1.0.1 is not updated to the latest portal version which is 0.3.0 which is updated specifically to support flutter 1.22.0.
> 
> So that's the only change.

Also you could look into that issue more if you are seeing anything else with flutter 1.22.0, but when I simply changed the portal version it fixed.

**Comment by krishnakumarcn** [comment]
Effectively this PR only contains that change along with the Flutter 1.22.0 changes to the pubspec.lock file. Could u check on the files changed tab?

**Comment by fayeed** [comment]
@krishnakumarcn Thanks for the PR

**Pull request merged**
